/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Create;

import Model.Storage;
import java.time.LocalTime;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Derek
 */
public class CreateTimePeriodPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateTimePeriodPanel
     */
    public CreateTimePeriodPanel() {
        initComponents();
    }
    
    private ComboBoxModel getCBScheduleHoursModel() {
        String[] items = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"};
        return new DefaultComboBoxModel(items);
    }
    
    private ComboBoxModel getCBHoursPeriodModel() {
        String[] items = {"AM", "PM"};
        return new DefaultComboBoxModel(items);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlStartAt = new javax.swing.JLabel();
        jlStartColon = new javax.swing.JLabel();
        jlEndColon = new javax.swing.JLabel();
        jlEndAt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jsEndMin = new javax.swing.JSpinner();
        jsStartMin = new javax.swing.JSpinner();
        jsStartHr = new javax.swing.JSpinner();
        jsEndHr = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        jlStartAt.setText("Starts At:");

        jlStartColon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlStartColon.setText(" : ");

        jlEndColon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlEndColon.setText(" : ");

        jlEndAt.setText("Ends At:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Time Period Information");

        jsEndMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jsStartMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jsStartHr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jsEndHr.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jButton2.setText("Add Time Period");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlStartAt)
                            .addComponent(jlEndAt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jsStartHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsEndHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlStartColon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsStartMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEndColon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsEndMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlStartAt)
                    .addComponent(jlStartColon)
                    .addComponent(jsStartMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsStartHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndAt)
                    .addComponent(jlEndColon)
                    .addComponent(jsEndMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsEndHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Storage.addNewTime_Period(LocalTime.of((int) jsStartHr.getValue(), (int) jsStartMin.getValue()), LocalTime.of((int) jsEndHr.getValue(), (int) jsEndMin.getValue()));
        clearItems();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlEndAt;
    private javax.swing.JLabel jlEndColon;
    private javax.swing.JLabel jlStartAt;
    private javax.swing.JLabel jlStartColon;
    private javax.swing.JSpinner jsEndHr;
    private javax.swing.JSpinner jsEndMin;
    private javax.swing.JSpinner jsStartHr;
    private javax.swing.JSpinner jsStartMin;
    // End of variables declaration//GEN-END:variables

    private void clearItems() {
        jsStartHr.setValue(0);
        jsStartMin.setValue(0);
        jsEndHr.setValue(0);
        jsEndMin.setValue(0);
    }
}
