package View;

import View.Create.*;
import View.Data.*;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Derek
 */
public class DemonstrationFrame extends javax.swing.JFrame {

    public static int openFrameCount = 0;
    public static final int XOFFSET = 30, YOFFSET = 30;

    /**
     * Creates new form TestFrame
     */
    public DemonstrationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmNew = new javax.swing.JMenu();
        jmiNewFaculty = new javax.swing.JMenuItem();
        jmiNewTime = new javax.swing.JMenuItem();
        jmiNewRoom = new javax.swing.JMenuItem();
        jmiNewCourse = new javax.swing.JMenuItem();
        jmiNewSection = new javax.swing.JMenuItem();
        jmiNewFCA = new javax.swing.JMenuItem();
        jmData = new javax.swing.JMenu();
        jmiDataFaculty = new javax.swing.JMenuItem();
        jmiDataTime = new javax.swing.JMenuItem();
        jmiDataRoom = new javax.swing.JMenuItem();
        jmiDataCourse = new javax.swing.JMenuItem();
        jmiDataSection = new javax.swing.JMenuItem();
        jmiDataFCA = new javax.swing.JMenuItem();
        jmCalView = new javax.swing.JMenu();
        jmiCVFaculty = new javax.swing.JMenuItem();
        jmiCVRoom = new javax.swing.JMenuItem();
        jmCVCL = new javax.swing.JMenu();
        jmiCVCLFCA = new javax.swing.JMenuItem();
        jmiCVCLCourse = new javax.swing.JMenuItem();
        jmiCVCLSections = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );

        jmFile.setText("File");

        jMenuItem1.setText("Import");
        jmFile.add(jMenuItem1);

        jMenuItem2.setText("Export");
        jmFile.add(jMenuItem2);

        jMenuBar1.add(jmFile);

        jmNew.setText("New");

        jmiNewFaculty.setText("Faculty");
        jmiNewFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewFacultyActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewFaculty);

        jmiNewTime.setText("Time");
        jmiNewTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewTimeActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewTime);

        jmiNewRoom.setText("Room");
        jmiNewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewRoomActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewRoom);

        jmiNewCourse.setText("Course");
        jmiNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewCourseActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewCourse);

        jmiNewSection.setText("Section");
        jmiNewSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewSectionActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewSection);

        jmiNewFCA.setText("Final Course Assignment");
        jmiNewFCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewFCAActionPerformed(evt);
            }
        });
        jmNew.add(jmiNewFCA);

        jMenuBar1.add(jmNew);

        jmData.setText("Data");

        jmiDataFaculty.setText("Faculty");
        jmiDataFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataFacultyActionPerformed(evt);
            }
        });
        jmData.add(jmiDataFaculty);

        jmiDataTime.setText("Time");
        jmiDataTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataTimeActionPerformed(evt);
            }
        });
        jmData.add(jmiDataTime);

        jmiDataRoom.setText("Room");
        jmiDataRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataRoomActionPerformed(evt);
            }
        });
        jmData.add(jmiDataRoom);

        jmiDataCourse.setText("Course");
        jmiDataCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataCourseActionPerformed(evt);
            }
        });
        jmData.add(jmiDataCourse);

        jmiDataSection.setText("Section");
        jmData.add(jmiDataSection);

        jmiDataFCA.setText("Final Course Assignment");
        jmiDataFCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDataFCAActionPerformed(evt);
            }
        });
        jmData.add(jmiDataFCA);

        jMenuBar1.add(jmData);

        jmCalView.setText("Calendar View");

        jmiCVFaculty.setText("By Faculty");
        jmiCVFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCVFacultyActionPerformed(evt);
            }
        });
        jmCalView.add(jmiCVFaculty);

        jmiCVRoom.setText("By Room");
        jmCalView.add(jmiCVRoom);

        jmCVCL.setText("By Custom List");

        jmiCVCLFCA.setText("Final Course Assignments");
        jmCVCL.add(jmiCVCLFCA);

        jmiCVCLCourse.setText("Courses");
        jmCVCL.add(jmiCVCLCourse);

        jmiCVCLSections.setText("Sections");
        jmCVCL.add(jmiCVCLSections);

        jmCalView.add(jmCVCL);

        jMenuBar1.add(jmCalView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewRoomActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Room", false, true, true, true);
        jif.setBounds(0, 0, 427, 325);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateRoomPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewRoomActionPerformed

    private void jmiNewFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewFacultyActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Faculty", true, true, true, true);
        jif.setBounds(0, 0, 430, 370);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateFacultyPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewFacultyActionPerformed

    private void jmiNewSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewSectionActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Section", true, true, true, true);
        jif.setBounds(0, 0, 465, 465);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateSectionPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewSectionActionPerformed

    private void jmiNewTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewTimeActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Time", true, true, true, true);
        jif.setBounds(0, 0, 300, 260);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateTimePeriodPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewTimeActionPerformed

    private void jmiNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewCourseActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Course", true, true, true, true);
        jif.setBounds(0, 0, 475, 485);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateCoursePanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewCourseActionPerformed

    private void jmiNewFCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewFCAActionPerformed
        JInternalFrame jif = new JInternalFrame("New: Final Course Assignment", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new CreateFinalCourseAssignmentPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiNewFCAActionPerformed

    private void jmiDataFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataFacultyActionPerformed
        JInternalFrame jif = new JInternalFrame("Data: Faculty", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new DataFacultyPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiDataFacultyActionPerformed

    private void jmiDataTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataTimeActionPerformed
        JInternalFrame jif = new JInternalFrame("Data: Time Period", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new DataTimePeriodPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiDataTimeActionPerformed

    private void jmiDataRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataRoomActionPerformed
        JInternalFrame jif = new JInternalFrame("Data: Room", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new DataRoomPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiDataRoomActionPerformed

    private void jmiDataCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataCourseActionPerformed
        JInternalFrame jif = new JInternalFrame("Data: Course", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new DataCoursePanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }//GEN-LAST:event_jmiDataCourseActionPerformed

    private void jmiDataFCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDataFCAActionPerformed
        JInternalFrame jif = new JInternalFrame("Data: Final Course Assignment", true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        JPanel p = new DataFinalCourseAssignmentPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
        
        
    }//GEN-LAST:event_jmiDataFCAActionPerformed

    private void jmiCVFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCVFacultyActionPerformed
        // TODO Find Courses Teacher is in, Make Events, Place in Weekly View and show
    }//GEN-LAST:event_jmiCVFacultyActionPerformed

    
    public  void createNewPanel(JPanel p, String title) {
        JInternalFrame jif = new JInternalFrame(title, true, true, true, true);
        jif.setBounds(0, 0, 700, 720);
        jif.setLocation(XOFFSET * openFrameCount, YOFFSET * openFrameCount);
        openFrameCount++;
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
        jif.toFront();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemonstrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmCVCL;
    private javax.swing.JMenu jmCalView;
    private javax.swing.JMenu jmData;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenu jmNew;
    private javax.swing.JMenuItem jmiCVCLCourse;
    private javax.swing.JMenuItem jmiCVCLFCA;
    private javax.swing.JMenuItem jmiCVCLSections;
    private javax.swing.JMenuItem jmiCVFaculty;
    private javax.swing.JMenuItem jmiCVRoom;
    private javax.swing.JMenuItem jmiDataCourse;
    private javax.swing.JMenuItem jmiDataFCA;
    private javax.swing.JMenuItem jmiDataFaculty;
    private javax.swing.JMenuItem jmiDataRoom;
    private javax.swing.JMenuItem jmiDataSection;
    private javax.swing.JMenuItem jmiDataTime;
    private javax.swing.JMenuItem jmiNewCourse;
    private javax.swing.JMenuItem jmiNewFCA;
    private javax.swing.JMenuItem jmiNewFaculty;
    private javax.swing.JMenuItem jmiNewRoom;
    private javax.swing.JMenuItem jmiNewSection;
    private javax.swing.JMenuItem jmiNewTime;
    // End of variables declaration//GEN-END:variables
}
