package View;


import Calendar.*;
import Model.*;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Derek
 */
public class DemonstrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public DemonstrationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmiFaculty = new javax.swing.JMenuItem();
        jmiTime = new javax.swing.JMenuItem();
        jmiRoom = new javax.swing.JMenuItem();
        jmiSection = new javax.swing.JMenuItem();
        jmiCourse = new javax.swing.JMenuItem();
        jmiFCA = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1064, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("New");

        jmiFaculty.setText("Faculty");
        jmiFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFacultyActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFaculty);

        jmiTime.setText("Time");
        jmiTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTimeActionPerformed(evt);
            }
        });
        jMenu2.add(jmiTime);

        jmiRoom.setText("Room");
        jmiRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRoomActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRoom);

        jmiSection.setText("Section");
        jmiSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSectionActionPerformed(evt);
            }
        });
        jMenu2.add(jmiSection);

        jmiCourse.setText("Course");
        jmiCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCourseActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCourse);

        jmiFCA.setText("Final Course Assignment");
        jmiFCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFCAActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFCA);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenu4.setText("Student Schedule");

        jMenu5.setText("Coming Soon...");
        jMenu4.add(jMenu5);

        jMenu3.add(jMenu4);

        jMenu6.setText("Example Weekly Calendar");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRoomActionPerformed
        JInternalFrame jif = new JInternalFrame("New Room", false, true, true, true);
        jif.setBounds(0,0,427,325);
        JPanel p = new CreateRoomPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiRoomActionPerformed

    private void jmiFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFacultyActionPerformed
        JInternalFrame jif = new JInternalFrame("New Faculty", false, true, true, true);
        jif.setBounds(0,0,430,370);
        JPanel p = new CreateFacultyPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiFacultyActionPerformed

    private void jmiSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSectionActionPerformed
        JInternalFrame jif = new JInternalFrame("New Section", false, true, true, true);
        jif.setBounds(0,0,50,50);
        JPanel p = new CreateSectionPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiSectionActionPerformed

    private void jmiTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTimeActionPerformed
        JInternalFrame jif = new JInternalFrame("New Time", false, true, true, true);
        jif.setBounds(0,0,300,260);
        JPanel p = new CreateTimePeriodPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiTimeActionPerformed

    private void jmiCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCourseActionPerformed
        JInternalFrame jif = new JInternalFrame("New Course", false, true, true, true);
        jif.setBounds(0,0,455,435);
        JPanel p = new CreateCoursePanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiCourseActionPerformed

    private void jmiFCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFCAActionPerformed
        JInternalFrame jif = new JInternalFrame("New Final Course Assignment", false, true, true, true);
        jif.setBounds(0,0,50,50);
        JPanel p = new CreateFinalCourseAssignmentPanel();
        jif.add(p);
        jif.setVisible(true);
        jDesktop.add(jif);
    }//GEN-LAST:event_jmiFCAActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        JInternalFrame jif = new JInternalFrame("Weekly Calendar", true, true, true, true);
        jif.setBounds(0,0,1000,900);
        
        ArrayList<CalendarEvent> events = new ArrayList<>();
        for(Final_Course_Assignment fca:Storage.copyFCA()){
            //TODO: Color, ETC
            //events.addAll(fcaToCalendarEvent(fca, ))
        }
            
        WeekCalendar cal = new WeekCalendar(events);

        cal.addCalendarEventClickListener(e -> System.out.println(e.getCalendarEvent()));
        cal.addCalendarEmptyClickListener(e -> {
            System.out.println(e.getDateTime());
            System.out.println(Calendar.roundTime(e.getDateTime().toLocalTime(), 30));
        });

        JButton goToTodayBtn = new JButton("Today");
        goToTodayBtn.addActionListener(e -> cal.goToToday());

        JButton nextWeekBtn = new JButton(">");
        nextWeekBtn.addActionListener(e -> cal.nextWeek());

        JButton prevWeekBtn = new JButton("<");
        prevWeekBtn.addActionListener(e -> cal.prevWeek());

        JButton nextMonthBtn = new JButton(">>");
        nextMonthBtn.addActionListener(e -> cal.nextMonth());

        JButton prevMonthBtn = new JButton("<<");
        prevMonthBtn.addActionListener(e -> cal.prevMonth());

        JPanel weekControls = new JPanel();
        weekControls.add(prevMonthBtn);
        weekControls.add(prevWeekBtn);
        weekControls.add(goToTodayBtn);
        weekControls.add(nextWeekBtn);
        weekControls.add(nextMonthBtn);

        jif.add(weekControls, BorderLayout.NORTH);

        jif.add(cal, BorderLayout.CENTER);
        jif.setSize(1000, 900);
        jif.setVisible(true);
    }//GEN-LAST:event_jMenu6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemonstrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemonstrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiCourse;
    private javax.swing.JMenuItem jmiFCA;
    private javax.swing.JMenuItem jmiFaculty;
    private javax.swing.JMenuItem jmiRoom;
    private javax.swing.JMenuItem jmiSection;
    private javax.swing.JMenuItem jmiTime;
    // End of variables declaration//GEN-END:variables
}
