/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Data;

import Calendar.CalendarEvent;
import Calendar.CourseToEvents;
import Calendar.CreatePanels;
import Calendar.WeekCalendar;
import Main.ApplicationFrame;
import Main.SQLPreparedStatements;
import View.Item.ItemFinalCourseAssignmentPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Derek
 */
public class DataFinalCourseAssignmentPanel extends javax.swing.JPanel {

    int visual;

    /**
     * Creates new form DataFacultyPanel
     */
    public DataFinalCourseAssignmentPanel(int visual) {
        this.visual = visual;
        initComponents();
        if (visual == 1) {
            jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        } else {
            jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
    }

    public DefaultListModel createFCAList() {
        ArrayList<ArrayList> fcas = SQLPreparedStatements.getFCA();

        DefaultListModel fca = new DefaultListModel();

        for (int i = 0; i < fcas.get(1).size(); i++) {
            ArrayList<Object> course = SQLPreparedStatements.getSingleCourse((String) fcas.get(3).get(i));
            fca.addElement(course.get(0) + " " + course.get(1) + " " + fcas.get(2).get(i));
        }
        return fca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Final Course Assignment Information");

        jList1.setModel(createFCAList());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            if (visual == 0) {
                singleItem();
            } else if (visual == 1) {
                calendarStuff();
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (visual == 1 && evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_SPACE) {
            calendarStuff();
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void calendarStuff() {
        ArrayList<ArrayList> fca = SQLPreparedStatements.getFCA();
        ArrayList<CalendarEvent> fcas = new ArrayList<>();
        for (int index : jList1.getSelectedIndices()) {
            String course_id = (String) fca.get(3).get(index);
            String section_num = (String) fca.get(2).get(index);
            Date start_date = (Date) fca.get(6).get(index);
            Date end_date = (Date) fca.get(7).get(index);
            int days = (int) fca.get(8).get(index);
            Time start_time = (Time) SQLPreparedStatements.getSingleTime((int) fca.get(5).get(index)).get(1);
            Time end_time = (Time) SQLPreparedStatements.getSingleTime((int) fca.get(5).get(index)).get(2);

            fcas.addAll(CourseToEvents.fcaToCalendarEvent(course_id, section_num, "COURSE SUB - NUM - SECTION", start_date.toLocalDate(), end_date.toLocalDate(), start_time.toLocalTime(), end_time.toLocalTime(), days));
        }
        JInternalFrame jif = new JInternalFrame("Calendar: FCA's", true, true, true, true);
        jif.setBounds(0, 0, 1000, 900);
        jif.setLocation(ApplicationFrame.XOFFSET * ApplicationFrame.openFrameCount, ApplicationFrame.YOFFSET * ApplicationFrame.openFrameCount);
        ApplicationFrame.openFrameCount++;

        WeekCalendar cal = CreatePanels.createWeekCalendarPanel(fcas);

        jif.add(CreatePanels.createWeekControlPanel(cal), BorderLayout.NORTH);
        jif.add(cal, BorderLayout.CENTER);
        jif.setVisible(true);
        ApplicationFrame.jDesktop.add(jif);
        jif.toFront();
    }

    private void singleItem() {

        ArrayList<ArrayList> fca = SQLPreparedStatements.getFCA();
        String course_id = (String) fca.get(3).get(jList1.getSelectedIndex());
        String section_num = (String) fca.get(2).get(jList1.getSelectedIndex());

        JInternalFrame jif = new JInternalFrame("Item: FCA " + course_id + " - " + section_num, true, true, true, true);
        jif.setBounds(0, 0, 400, 300);
        jif.setLocation(ApplicationFrame.XOFFSET * ApplicationFrame.openFrameCount, ApplicationFrame.YOFFSET * ApplicationFrame.openFrameCount);
        ApplicationFrame.openFrameCount++;
        jif.add((new ItemFinalCourseAssignmentPanel(SQLPreparedStatements.getSingleFCA(course_id, section_num))));
        jif.setVisible(true);
        ApplicationFrame.jDesktop.add(jif);
        jif.toFront();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
